image: sikalabs/ci

stages:
  - build
  - deploy_dev
  - deploy_dev_test
  - deploy_prod
  - deploy_prod_test

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
  HOST_DEV: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$BASE_DOMAIN
  HOST_PROD: hello-server.$BASE_DOMAIN
  ENV: dev

build_bin:
  image: golang:1.18
  stage: build
  parallel:
    matrix:
      - GOOS: linux
        GOARCH:
          - amd64
          - arm64
      - GOOS: darwin
        GOARCH:
          - amd64
          - arm64
      - GOOS: windows
        GOARCH:
          - amd64
  script:
    - go build
  artifacts:
    paths:
      - hello-server
      - hello-server.exe

build_docker:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE

.dev:
  stage: deploy_dev
  needs:
    - build_docker

.deploy:
  script:
    - helm repo add sikalabs https://helm.sikalabs.io
    - helm upgrade --install $CI_COMMIT_REF_SLUG-$ENV --create-namespace sikalabs/one-image
      --set host=$HOST
      --set image=$IMAGE
    - slu wait-for tls -a $HOST:443 --timeout 60

deploy_dev:
  extends:
    - .dev
    - .deploy
  variables:
    HOST: $HOST_DEV
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: stop_dev

stop_dev:
  extends:
    - .dev
  when: manual
  variables:
    GIT_STRATEGY: none
  script:
    - helm uninstall $CI_COMMIT_REF_SLUG-$ENV
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    action: stop

deploy_dev_test:
  stage: deploy_dev_test
  needs:
    - deploy_dev
  script:
    - curl -L https://$HOST_DEV

.prod_only:
  rules:
    - if: $CI_COMMIT_REF_SLUG == "master"

deploy_prod:
  extends:
    - .deploy
    - .prod_only
  stage: deploy_prod
  needs:
    - deploy_dev_test
  when: manual
  allow_failure: false
  variables:
    HOST: $HOST_PROD
    ENV: prod
  environment:
    name: prod
    url: https://hello-server.$BASE_DOMAIN

deploy_prod_test:
  extends:
    - .prod_only
  stage: deploy_prod_test
  needs:
    - deploy_prod
  script:
    - curl -L https://$HOST_PROD
