image: sikalabs/ci

stages:
  - build
  - deploy_dev
  - deploy_dev_test
  - deploy_prod
  - deploy_prod_test

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID

build_bin:
  image: golang:1.18
  stage: build
  parallel:
    matrix:
      - GOOS: linux
        GOARCH:
          - amd64
          - arm64
      - GOOS: darwin
        GOARCH:
          - amd64
          - arm64
      - GOOS: windows
        GOARCH:
          - amd64
  script:
    - go build
  artifacts:
    paths:
      - hello-server
      - hello-server.exe

build_docker:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE
